# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37ac0c18d0fcc92c8fc722ae6a8dcfb238ea221e40f1cd525d7801a179e5cf053b093e9913c79ba383c26d60a24d6917d9d33ec7b01b2b6314988a95aec36d50

test:
  secret_key_base: 7648f01ba932732a2d876c7700c443577401fc8592bc340d72db2138dd525023cf5be2c5d7cd639204a9289f7977d7393800dfea7084d651f9c4784f1a625aa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
